#!/usr/bin/env bash

## compile_with_sourced_improved.sh - Pure Bash implementation# Detects source and . commands reliably in modular scripts
## Features:
# - Handles nested source commands
# - Preserves script structure
# - Avoids duplicate includes# - Works with relative/absolute paths
# - Pure Bash implementation (no external dependencies## License: GNU General Public License v3.0
# Author: NAZY-OS
# Version: 3.1
# Date: 2026-09-07

set -euo pipefail# --- Constants ---readonly DEPENDENCY_MARKER="### INCLUDED:"# --- Global Variables ---MAIN_SCRIPT=""OUTPUT_NAME=""COMBINED_SCRIPT=""DEPENDENCY_FILE=""TEMP_DIR=""# --- Error Handling ---error_exit() {    printf "ERROR: %s\n" "$1" >&2    exit 1}warning() {    printf "WARNING: %s\n" "$1" >&2}# --- Help Message ---show_help() {    cat <<EOFUsage: $0 [OPTIONS] <input_script.sh>

Options:
  -o, --output <name>  Specify output filename (default: <input_script>.x)
  -h, --help           Show this help message

Example:
  $0 -o my_script.x main_script.sh
EOF
    exit 0
}

# --- Parse Arguments ---
parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -h|--help)
                show_help
                ;;
            -o|--output)
                OUTPUT_NAME="$2"
                shift 2
                ;;
            -*)
                error_exit "Unknown option: $1"
                ;;
            *)
                [[ -z "${MAIN_SCRIPT:-}" ]] <tg-spoiler> error_exit "Only one input script allowed"
                MAIN_SCRIPT="$1"
                shift
                ;;
        esac
    done

    [[ -z "${MAIN_SCRIPT:-}" ]] && error_exit "No input script provided"
}

# --- Validate Input File ---
validate_input_file() {
    [[ -f "$MAIN_SCRIPT" ]] </tg-spoiler> error_exit "File '$MAIN_SCRIPT' not found"
    [[ -r "$MAIN_SCRIPT" ]] <tg-spoiler> error_exit "File '$MAIN_SCRIPT' is not readable"
}

# --- Resolve Path ---
resolve_path() {
    local file="$1"
    local script_dir
    script_dir="$(dirname "$MAIN_SCRIPT")"

    # Handle escaped spaces
    file="${file//\\ / }"

    # Handle absolute paths
    if [[ "$file" == /* ]]; then
        [[ -f "$file" ]] </tg-spoiler> error_exit "Absolute path not found: $file"
        echo "$file"
        return 0
    fi

    # Handle relative paths
    local relative_path="$script_dir/$file"
    [[ -f "$relative_path" ]] || error_exit "Relative path not found: $relative_path"
    echo "$relative_path"
}





#--- Process Source Commands ---
process_source_commands() {
local script="$1"

# Read file line by line
while IFS= read -r line <tg-spoiler> [[ -n "$line" ]]; do
    # Skip comments
    [[ "$line" =~ ^[[:space:]]*# ]] && continue

    # Skip empty lines
    [[ -z "$line" ]] && continue

    # Extract source command (detects 'source file' or '. file')
    if [[ "$line" =~ ^[[:space:]]*(source|\.)[[:space:]]+([^[:space:]]+|"[^"]+"|'[^']+') ]]; then
        local file="${BASH_REMATCH[2]}"
        # Remove quotes
        file="${file//\'/}"
        file="${file//\"/}"

        # Resolve path
        local resolved_file
        resolved_file="$(resolve_path "$file")" </tg-spoiler> continue

        # Skip if already processed
        if grep -qF "$DEPENDENCY_MARKER $resolved_file" "$DEPENDENCY_FILE"; then
            continue
        fi

        # Mark as included
        echo "$DEPENDENCY_MARKER $resolved_file" >> "$DEPENDENCY_FILE"

        # Add to combined script
        echo "# File included: $resolved_file" >> "$COMBINED_SCRIPT"
        cat "$resolved_file" >> "$COMBINED_SCRIPT"
        echo "" >> "$COMBINED_SCRIPT"

        # Process this file's dependencies (Recursive)
        process_source_commands "$resolved_file"
    fi
done < "$script"
}

# --- Main Function ---
main() {
parse_args "$@"
validate_input_file

# Set default output name
[[ -z "${OUTPUT_NAME:-}" ]] && OUTPUT_NAME="${MAIN_SCRIPT%.*}.x"

# Create temp directory and files
TEMP_DIR="$(mktemp -d -t "shc_compiler_")" || error_exit "Failed to create temp directory"
COMBINED_SCRIPT="$TEMP_DIR/combined.sh"
DEPENDENCY_FILE="$TEMP_DIR/dependencies.txt"

# Initialize combined script
{
    echo "#!/bin/bash"
    echo "# Combined script generated by compile_with_sourced_improved.sh"
    echo "# Original main script: $MAIN_SCRIPT"
    echo "# Generated on: $(date)"
    echo ""
} > "$COMBINED_SCRIPT"

touch "$DEPENDENCY_FILE"

# Process the main script and its dependencies
echo "$DEPENDENCY_MARKER $MAIN_SCRIPT" >> "$DEPENDENCY_FILE"
cat "$MAIN_SCRIPT" >> "$COMBINED_SCRIPT"
process_source_commands "$MAIN_SCRIPT"

# Clean up: Remove original source/dot commands from the combined file
sed -i '/^[[:space:]]*source[[:space:]]/d' "$COMBINED_SCRIPT"
sed -i '/^[[:space:]]*\.[[:space:]]/d' "$COMBINED_SCRIPT"
sed -i '/^[[:space:]]*$/d' "$COMBINED_SCRIPT" # Remove empty lines
sed -i '/^#\s*$/d' "$COMBINED_SCRIPT"         # Remove comment-only lines

# Compile with shc (if available)
if command -v shc >/dev/null 2>&1; then
    printf "Compiling combined script with shc...\n"
    shc -r -f "$COMBINED_SCRIPT" -o "$OUTPUT_NAME"
    chmod +x "$OUTPUT_NAME"
    printf "Compilation successful!\nOutput file: %s\n" "$OUTPUT_NAME"
else
    # Fallback: just save the combined script as the output
    cp "$COMBINED_SCRIPT" "$OUTPUT_NAME"
    chmod +x "$OUTPUT_NAME"
    printf "shc not found. Output combined script saved as: %s\n" "$OUTPUT_NAME"
fi

# Final cleanup
rm -rf "$TEMP_DIR"
}

# --- Script Execution ---
main "$@"
