#!/usr/bin/env bash
#
# compile_with_sourced.sh - Shell Script Compiler with Sourced File Inclusion
#
# Copyright (C) 2024-2026 John Doe <john.doe@example.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Version: 1.1
# Name: Shell Script Compiler with Sourced File Inclusion
# Author: John Doe
# License: GNU General Public License v3.0
# Date: 2024-09-07

set -euo pipefail

# Check if shc is installed
if ! command -v shc &> /dev/null; then
    echo "Error: shc is not installed. Please install it first."
    echo "On Debian/Ubuntu: sudo apt-get install shc"
    echo "On RHEL/CentOS: sudo yum install shc"
    echo "On Arch Linux: sudo pacman -S shc"
    exit 1
fi

# Check if input file is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 <main_script.sh>"
    echo "Example: $0 my_script.sh"
    exit 1
fi

# Validate input file
if [ ! -f "$1" ]; then
    echo "Error: File '$1' not found or not readable"
    exit 1
fi

MAIN_SCRIPT="$1"
OUTPUT_NAME="${MAIN_SCRIPT%.*}"  # Remove extension
TEMP_DIR=$(mktemp -d)
COMBINED_SCRIPT="$TEMP_DIR/combined.sh"
FINAL_OUTPUT="${OUTPUT_NAME}.x"

# Create a temporary directory for processing
cp "$MAIN_SCRIPT" "$TEMP_DIR/"
cd "$TEMP_DIR" || exit 1

# Function to process sourced files recursively
process_sourced_files() {
    local script="$1"
    # Find all source commands (source, ., and variations with spaces)
    local sourced_files=($(grep -oE '^\s*(source\s+[^[:space:]]+|source\s+["\'][^"\']+["\']|\.\s+[^[:space:]]+|\.\s+["\'][^"\']+["\'])' "$script" | \
                          sed -E "s/^\s*(source|source|\.)\s+['\"]?([^'\"\s]+)['\"]?/\2/" | sort -u))

    for file in "${sourced_files[@]}"; do
        # Skip if file is empty or contains only whitespace
        if [ -z "$file" ] || [[ "$file" =~ ^[[:space:]]*$ ]]; then
            continue
        fi

        # Resolve relative paths
        if [[ "$file" != /* ]]; then
            file="$(dirname "$script")/$file"
        fi

        if [ -f "$file" ]; then
            # Only process if not already included
            if ! grep -qF "### INCLUDED: $file" "$COMBINED_SCRIPT" 2>/dev/null; then
                echo "### INCLUDED: $file" >> "$COMBINED_SCRIPT"
                cat "$file" >> "$COMBINED_SCRIPT"
                process_sourced_files "$file"
            fi
        else
            echo "Warning: Could not find sourced file: $file"
        fi
    done
}

# Initialize combined script
{
    echo "#!/bin/bash"
    echo "# Combined script generated by compile_with_sourced.sh"
    echo "# Original main script: $MAIN_SCRIPT"
    echo "# Generated on: $(date)"
    echo ""
} > "$COMBINED_SCRIPT"

# Process the main script
cat "$MAIN_SCRIPT" >> "$COMBINED_SCRIPT"
process_sourced_files "$MAIN_SCRIPT"

# Remove source commands from combined script
sed -i '/^\s*source\s/d' "$COMBINED_SCRIPT"
sed -i '/^\s*\.\s/d' "$COMBINED_SCRIPT"

# Remove empty lines and comments that might have been created
sed -i '/^[[:space:]]*$/d' "$COMBINED_SCRIPT"
sed -i '/^#\s*$/d' "$COMBINED_SCRIPT"

# Compile with shc
echo "Compiling combined script with shc..."
shc -r -f combined.sh -o "$FINAL_OUTPUT"

# Set executable permissions
chmod +x "$FINAL_OUTPUT"

# Clean up
cd ..
rm -rf "$TEMP_DIR"

echo "Compilation successful!"
echo "Output file: $FINAL_OUTPUT"
echo "You can now run it with: ./$FINAL_OUTPUT"
