#!/usr/bin/env bash
#
# compile_with_sourced.sh - Compiles a shell script with shc including all sourced files
#
# Copyright (C) 2024-2026 John Doe <john.doe@example.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Version: 1.1
# Name: Shell Script Compiler with Sourced File Inclusion
# Author: John Doe
# License: GNU General Public License v3.0
# Date: 2024-09-07

set -euo pipefail

# Check if shc is installed
if ! command -v shc &> /dev/null; then
    echo "Error: shc is not installed. Please install it first."
    echo "On Debian/Ubuntu: sudo apt-get install shc"
    echo "On RHEL/CentOS: sudo yum install shc"
    echo "On Arch Linux: sudo pacman -S shc"
    exit 1
fi

# Check if input file is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 <main_script.sh>"
    echo "Example: $0 my_script.sh"
    exit 1
fi

# Validate input file
if [ ! -f "$1" ]; then
    echo "Error: File '$1' not found or not readable"
    exit 1
fi

MAIN_SCRIPT="$1"
OUTPUT_NAME="${MAIN_SCRIPT%.*}"  # Remove extension
TEMP_DIR=$(mktemp -d)
COMBINED_SCRIPT="$TEMP_DIR/combined.sh"
FINAL_OUTPUT="${OUTPUT_NAME}.x"
DEPENDENCY_FILE="$TEMP_DIR/dependencies.txt"

# Create a temporary directory for processing
cp "$MAIN_SCRIPT" "$TEMP_DIR/"
cd "$TEMP_DIR" || exit 1

# Function to resolve file paths
resolve_path() {
    local file="$1"
    local script_dir="$(dirname "$MAIN_SCRIPT")"

    # Handle absolute paths
    if [[ "$file" == /* ]]; then
        if [ -f "$file" ]; then
            echo "$file"
        else
            echo "Warning: Absolute path not found: $file" >&2
            return 1
        fi
    # Handle relative paths
    else
        local relative_path="$script_dir/$file"
        if [ -f "$relative_path" ]; then
            echo "$relative_path"
        else
            echo "Warning: Relative path not found: $relative_path" >&2
            return 1
        fi
    fi
}

# Function to process sourced files recursively
process_sourced_files() {
    local script="$1"
    local script_dir="$(dirname "$script")"

    # Find all source commands (source, ., and variations)
    grep -oE '^\s*(source\s+[^[:space:]]+|source\s+["\'][^"\']+["\']|\.\s+[^[:space:]]+|\.\s+["\'][^"\']+["\'])' "$script" | while read -r line; do
        # Extract the filename
        local file=$(echo "$line" | sed -E "s/^\s*(source|source|\.)\s+['\"]?([^'\"\s]+)['\"]?/\2/")

        # Resolve the path
        local resolved_file
        resolved_file=$(resolve_path "$file") || continue

        # Skip if already processed
        if grep -qF "### INCLUDED: $resolved_file" "$DEPENDENCY_FILE" 2>/dev/null; then
            continue
        fi

        # Mark as included
        echo "### INCLUDED: $resolved_file" >> "$DEPENDENCY_FILE"

        # Add to combined script
        echo "# File included: $resolved_file" >> "$COMBINED_SCRIPT"
        cat "$resolved_file" >> "$COMBINED_SCRIPT"
        echo "" >> "$COMBINED_SCRIPT"

        # Process this file's dependencies
        process_sourced_files "$resolved_file"
    done
}

# Initialize files
{
    echo "#!/bin/bash"
    echo "# Combined script generated by compile_with_sourced.sh"
    echo "# Original main script: $MAIN_SCRIPT"
    echo "# Generated on: $(date)"
    echo ""
} > "$COMBINED_SCRIPT"

touch "$DEPENDENCY_FILE"

# Process the main script and its dependencies
echo "### INCLUDED: $MAIN_SCRIPT" >> "$DEPENDENCY_FILE"
cat "$MAIN_SCRIPT" >> "$COMBINED_SCRIPT"
process_sourced_files "$MAIN_SCRIPT"

# Remove source commands from combined script
sed -i '/^\s*source\s/d' "$COMBINED_SCRIPT"
sed -i '/^\s*\.\s/d' "$COMBINED_SCRIPT"

# Remove empty lines and comments that might have been created
sed -i '/^[[:space:]]*$/d' "$COMBINED_SCRIPT"
sed -i '/^#\s*$/d' "$COMBINED_SCRIPT"

# Compile with shc
echo "Compiling combined script with shc..."
shc -r -f combined.sh -o "$FINAL_OUTPUT"

# Set executable permissions
chmod +x "$FINAL_OUTPUT"

# Clean up
cd ..
rm -rf "$TEMP_DIR"

echo "Compilation successful!"
echo "Output file: $FINAL_OUTPUT"
echo "You can now run it with: ./$FINAL_OUTPUT"
