#!/usr/bin/env bash
#
# compile_with_sourced_improved.sh - Improved version of compile_with_sourced.sh
# Detects `source` and `.` commands more reliably, including edge cases.
#
# Features:
# - Handles relative/absolute paths (./, ../, /path/to/file)
# - Ignores comments (e.g., # source lib.sh)
# - Supports multi-line source commands
# - Resolves variables and command substitutions (e.g., source $VAR, source $(command))
# - Handles escaped spaces in filenames
# - Avoids false positives in conditionals (if/else) and other contexts
#
# Copyright (C) 2026 NAZY-OS
# License: GNU General Public License v3.0

# Version: 1.1
# scriptName: shc-compiler-modular.sh
# author: NAZY-OS
# license: GNU GPLv3

set -euo pipefail

# Check if shc is installed
if ! command -v shc &> /dev/null; then
    echo "Error: shc is not installed. Please install it first."
    echo "On Debian/Ubuntu: sudo apt-get install shc"
    echo "On RHEL/CentOS: sudo yum install shc"
    echo "On Arch Linux: sudo pacman -S shc"
    exit 1
fi

# Check if input file is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 <main_script.sh>"
    echo "Example: $0 my_script.sh"
    exit 1
fi

# Validate input file
if [ ! -f "$1" ]; then
    echo "Error: File '$1' not found or not readable"
    exit 1
fi

MAIN_SCRIPT="$1"
OUTPUT_NAME="${MAIN_SCRIPT%.*}"  # Remove extension
TEMP_DIR=$(mktemp -d)
COMBINED_SCRIPT="$TEMP_DIR/combined.sh"
FINAL_OUTPUT="${OUTPUT_NAME}.x"
DEPENDENCY_FILE="$TEMP_DIR/dependencies.txt"

# Create a temporary directory for processing
cp "$MAIN_SCRIPT" "$TEMP_DIR/"
cd "$TEMP_DIR" || exit 1

# Function to resolve file paths (supports ./, ../, /absolute/path, variables, etc.)
resolve_path() {
    local file="$1"
    local script_dir="$(dirname "$MAIN_SCRIPT")"

    # Handle command substitutions (e.g., source $(command))
    if [[ "$file" =~ \$(\(.*\)) ]]; then
        echo "Warning: Command substitution in source path detected: $file" >&2
        return 1
    fi

    # Handle variables (e.g., source $VAR)
    if [[ "$file" =~ \$\{?[A-Za-z_][A-Za-z0-9_]*\}? ]]; then
        echo "Warning: Variable in source path detected: $file" >&2
        return 1
    fi

    # Handle escaped spaces (e.g., "lib\ with\ spaces.sh")
    file="${file//\\ / }"

    # Handle absolute paths
    if [[ "$file" == /* ]]; then
        if [ -f "$file" ]; then
            echo "$file"
        else
            echo "Warning: Absolute path not found: $file" >&2
            return 1
        fi
    # Handle relative paths (./, ../)
    else
        local relative_path="$script_dir/$file"
        if [ -f "$relative_path" ]; then
            echo "$relative_path"
        else
            echo "Warning: Relative path not found: $relative_path" >&2
            return 1
        fi
    fi
}

# Improved function to process sourced files (handles edge cases)
process_sourced_files() {
    local script="$1"
    local script_dir="$(dirname "$script")"

    # Use awk to parse source/. commands more reliably
    # - Skips comments (lines starting with #)
    # - Handles multi-line commands
    # - Avoids false positives in conditionals
    awk '
        BEGIN { in_comment = 0; in_quote = 0; }
        {
            line = $0
            # Skip comments (lines starting with #)
            if (match(line, /^[[:space:]]*#/)) next
            # Handle multi-line commands (backslash at end of line)
            if (match(line, /\\$/)) {
                in_comment = 1
                next
            }
            if (in_comment) {
                in_comment = 0
                next
            }
            # Skip if not a source/. command
            if (!match(line, /(^|[[:space:]])(source|\\.)[[:space:]]/)) next
            # Extract the filename (handles quotes, spaces, and escapes)
            if (match(line, /(source|\\.)[[:space:]]+([^[:space:]]+|"[^"]+"|'\''[^'\'']+'\''|`[^`]+`)/)) {
                filename = substr(line, RSTART, RLENGTH)
                # Remove "source" or "." and trim whitespace
                gsub(/(source|\\.)[[:space:]]+/, "", filename)
                # Remove quotes and backticks
                gsub(/["'\'']|`/, "", filename)
                print filename
            }
        }
    ' "$script | while read -r file; do
        # Resolve the path
        local resolved_file
        resolved_file=$(resolve_path "$file") || continue

        # Skip if already processed
        if grep -qF "### INCLUDED: $resolved_file" "$DEPENDENCY_FILE" 2>/dev/null; then
            continue
        fi

        # Mark as included
        echo "### INCLUDED: $resolved_file" >> "$DEPENDENCY_FILE"

        # Add to combined script
        echo "# File included: $resolved_file" >> "$COMBINED_SCRIPT"
        cat "$resolved_file" >> "$COMBINED_SCRIPT"
        echo "" >> "$COMBINED_SCRIPT"

        # Process this file's dependencies
        process_sourced_files "$resolved_file"
    done
}

# Initialize files
{
    echo "#!/bin/bash"
    echo "# Combined script generated by compile_with_sourced_improved.sh"
    echo "# Original main script: $MAIN_SCRIPT"
    echo "# Generated on: $(date)"
    echo ""
} > "$COMBINED_SCRIPT"

touch "$DEPENDENCY_FILE"

# Process the main script and its dependencies
echo "### INCLUDED: $MAIN_SCRIPT" >> "$DEPENDENCY_FILE"
cat "$MAIN_SCRIPT" >> "$COMBINED_SCRIPT"
process_sourced_files "$MAIN_SCRIPT"

# Remove source commands from combined script (more thorough cleanup)
sed -i -E '/^\s*(source|\\.)\s/d' "$COMBINED_SCRIPT"
sed -i '/^[[:space:]]*$/d' "$COMBINED_SCRIPT"  # Remove empty lines
sed -i '/^#\s*$/d' "$COMBINED_SCRIPT"         # Remove comment-only lines

# Compile with shc
echo "Compiling combined script with shc..."
shc -r -f combined.sh -o "$FINAL_OUTPUT"

# Set executable permissions
chmod +x "$FINAL_OUTPUT"

# Clean up
cd ..
rm -rf "$TEMP_DIR"

echo "Compilation successful!"
echo "Output file: $FINAL_OUTPUT"
echo "You can now run it with: ./$FINAL_OUTPUT"
